---
name: App-ZofCMS-Plugin-JavaScriptMinifier
version: 0.0101
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: plugin for minifying JavaScript files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  JavaScript::Minifier: 1.05
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::JavaScriptMinifier:
    file: lib/App/ZofCMS/Plugin/JavaScriptMinifier.pm
    version: 0.0101
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
